name = "Stygian Tech"
author = "stygigoth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeb1117d39570b1d8eedb5666ad7262d169bc594f14e386bb077083b8d36fa86"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
