name = "Stygian Tech"
author = "stygigoth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7b1ae68958221a1f53d7a67b2294d8ce9d62ae5977c37cac9f6d9953811a8f6"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
