name = "Stygian Tech"
author = "stygigoth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22f5c53508d18f36347caf831864bd8eba24c8d59e50c9efe3e1f11b968b5f27"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
