name = "Stygian Tech"
author = "stygigoth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b5151410bb072e9f9d37208ba4d8a4812a1cad665876f0ab85ed637814db331"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
