name = "Stygian Tech"
author = "stygigoth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f72399a83ba6110fbcc6b9332780b52f105633afbdef52398b269d25a29618da"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
